TOKENS = [
    ' ',
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    '-',
    '(',
    ')',
    '/',
    '&',
    '.',
    "'",
    '+',
    ']',
    '[',
    ',',
    '"',
    ':',
    '%',
    ';',
    '>',
    '`',
    'œ',
    '£',
    '^',
    '~',
    '=',
    '}',
    '?',
    '@',
    '{',
    '!',
    '*',
    '_'
]

CLASSES = [
	'Opening balance for b/f bals(nonRTO) Opening Balance - S/C b/f',
	'Rent (P&L) Commissions on Rent',
	'Rent (P&L) Flat Refurbishment',
	'Rent (P&L) General non-recoverable repair',
	'Rent (P&L) Grants Received',
	'Rent (P&L) Insurance',
	'Rent (P&L) Lease Extension',
	'Rent (P&L) Legal Fees',
	'Rent (P&L) Letting Fee',
	'Rent (P&L) Loans',
	'Rent (P&L) Maintenance (non recoverable)',
	'Rent (P&L) Non-Recoverable Expenditure',
	'Rent (P&L) Refurbishment Fee',
	'Rent (P&L) Rent Payable',
	'Rent (P&L) Residuals - Service Charge',
	'Rent (P&L) Sale Proceeds',
	'Rent (P&L) Tenant Recharges',
	'Rent (P&L) Transfers - Property to Owner',
	'Rent (P&L) Utilities (non recoverable)',
	'Rent (P&L) Window Replacement',
	'Service Charge Abandoned Cars Search/ Removel',
	'Service Charge Asbestos Survey',
	'Service Charge Audit Fees',
	'Service Charge Boiler Repairs & Maintenance',
	'Service Charge Building Repairs & Maintenance',
	'Service Charge Caretakers Expenses',
	'Service Charge Caretakers Pay & NI',
	'Service Charge Caretakers Rent  C.Tax & Ins.',
	'Service Charge Caretakers Utilities',
	'Service Charge Caretaking Cleaning&Gardening',
	'Service Charge Communal Cleaning',
	'Service Charge Communal Electricity',
	'Service Charge Communal Lighting',
	'Service Charge Electrical Repairs & Testing',
	'Service Charge Emergency Lights Test & Maint',
	'Service Charge Entryphone',
	'Service Charge Fire Safety Eqpt Test & Maint',
	'Service Charge Fuels (gas & oil) Communal',
	'Service Charge Gardening',
	'Service Charge Insurance (service charge)',
	'Service Charge Lamp Replacement',
	'Service Charge Legal Fees',
	'Service Charge Legal Fees (SC)',
	'Service Charge Lift Renewal',
	'Service Charge Lift Repairs & Maintenance',
	'Service Charge Loans',
	'Service Charge Major Repairs',
	'Service Charge Management Fees',
	'Service Charge Palladin Hire',
	'Service Charge Pest Control',
	'Service Charge Refuse Collection',
	'Service Charge Residuals - Service Charge',
	'Service Charge Residuals to/from Rent',
	'Service Charge Risk Assessment Reports',
	'Service Charge Roofing',
	'Service Charge Roundings',
	'Service Charge Rubbish Clearance',
	'Service Charge Satellite Installation',
	'Service Charge Surveyors Fees',
	'Service Charge Transfer to Reserves',
	'Service Charge Water Mains Service Contract'
]
PATH_TO_TRAIN_DATA = './data/train.csv'
PATH_TO_VAL_DATA = './data/val.csv'
PATH_TO_TEST_DATA = './data/test.csv'
PATH_TO_SAVED_MODEL = './data/'